[package]
name = "rocket-app"
version = "0.1.0"
authors = ["vkotsiuba99"]
publish = false
edition = "2022"

[dependencies.rocket]
version = "~0.4"

[dependencies.rocket_contrib]
version = "~0.4"

[dependencies.rocket_codegen]
version = "~0.4"

[dependencies.serde]
version = "~1"

[dependencies.serde_derive]
version = "~1"

[dependencies.serde_json]
version = "~1"

[dependencies.uuid]
version = "~0.8"
features = ["serde", "v4"]

[dependencies.log]
version = "~0.4"
features = ["serde"]

[dependencies.env_logger]
version = "~0.8"

[dependencies.thiserror]
version = "~1"

[dependencies.auto_impl]
version = "~0.4"