[package]
name = "rocket-app"
version = "0.1.0"
authors = ["vkotsiuba99"]
publish = false
edition = "2022"

[dependencies]
rocket = "~0.4"
rocket_contrib = "~0.4"
rocket_codegen = "~0.4"

serde = "~1"
serde_derive = "~1"
serde_json = "~1"

uuid = { version = "~0.7", features = ["serde", "v4"] }

log = { version = "~0.4", features = ["serde"] }
env_logger = "~0.5"

failure = "~0.1"
failure_derive = "~0.1"

auto_impl = { version = "~0.3", features = ["nightly"] }